"""init

Revision ID: 285c0eaa142c
Revises: 9918fdaf35c1
Create Date: 2023-12-16 10:57:14.519312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285c0eaa142c'
down_revision = '9918fdaf35c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('genre_id', sa.BigInteger(), nullable=False))
    op.add_column('book', sa.Column('author_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'book', 'author', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'book', 'genre', ['genre_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'author_id')
    op.drop_column('book', 'genre_id')
    # ### end Alembic commands ###
