"""init

Revision ID: a51128d5ad79
Revises: 7f3cf9774afb
Create Date: 2023-12-19 10:54:42.923879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a51128d5ad79'
down_revision = '7f3cf9774afb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('file_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'book', 'file', ['file_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'file_id')
    # ### end Alembic commands ###
