"""init

Revision ID: caafa67d3a92
Revises: 285c0eaa142c
Create Date: 2023-12-16 11:14:01.563016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caafa67d3a92'
down_revision = '285c0eaa142c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
